name: Release

on:
  push:
    branches: ["main-dev"]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build_conan_packages_arm64:
    name: Build conan package for linux arm64
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main-dev' && github.event_name == 'workflow_dispatch' }}
    # needs: versioning
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get docker daemon IP
        id: dockerip
        run: |
          docker_ip=$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') && \
          echo "docker_ip=$docker_ip" >> "$GITHUB_OUTPUT"
      - name: Set new password for runner user
        id: userpass
        run: |
          user_pass="1122"
          echo "runner:$user_pass" | sudo chpasswd
          echo "user_pass=$user_pass" >> "$GITHUB_OUTPUT"
      - name: Create conan packages using buildx
        run: |
          docker buildx create --use
          docker buildx build \
          --platform "linux/arm64" \
          --build-arg docker_ip=${{ steps.dockerip.outputs.docker_ip }} \
          --build-arg user_pass=${{ steps.userpass.outputs.user_pass }} \
          --file ./Dockerfile \
          --tag gurgenyegoryan/ustore-deps:latest \
          --load .
      - name: Upload archives
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ustore_deps_arm_linux.tar.gz
          update_latest_release: true

  build_conan_pacjjkages_arm64:
    name: Build conannn package for linux arm64
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    # needs: versioning
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: 'main-dev'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get docker daemon IP
        id: dockerip
        run: |
          docker_ip=$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') && \
          echo "docker_ip=$docker_ip" >> "$GITHUB_OUTPUT"
      - name: Set new password for runner user
        id: userpass
        run: |
          user_pass="1122"
          echo "runner:$user_pass" | sudo chpasswd
          echo "user_pass=$user_pass" >> "$GITHUB_OUTPUT"
      - name: Create conan packages using buildx
        run: |
          docker buildx create --use
          docker buildx build \
          --platform "linux/arm64" \
          --build-arg docker_ip=${{ steps.dockerip.outputs.docker_ip }} \
          --build-arg user_pass=${{ steps.userpass.outputs.user_pass }} \
          --file ./Dockerfile \
          --tag gurgenyegoryan/ustore-deps:latest \
          --load .
      - name: Upload archives
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ustore_deps_arm_linux.tar.gz
          update_latest_release: true
